### ISSUE TITLE
Add /topics endpoint

### ISSUE THREAD

**Issue by stevepeak** [asyncy/hub#3]
Add a page for showing results by topics: `/topics/diff` or `/topics/diff+another` for two topics.

When you click on a topic it will navigate to `/topics/foobar`.

**Comment by abylaw** [comment]
It doesn't seem possible rn to search any service w/ (but not exclusively w/) a particular topic since using `condition` on `allServices` needs exact match. We'll need to add that.

It'd also be great to get wildcard operators on alias which would also improve search 👍

**Comment by stevepeak** [comment]
Waiting on https://github.com/asyncy/platform-bootstrap/issues/11

**Comment by stevepeak** [comment]
Supported via `/tags`
