### ISSUE TITLE
GitHub links are not derived from app_hidden.repos and app_public.owner_vcs

### ISSUE THREAD

**Issue by rajatjindal** [asyncy/hub#53]
e.g. https://hub.asyncy.com/service/blink-diff, https://hub.asyncy.com/service/yaml

the github link points to github.com/microservices, while the actual repos are hosted at github.com/microservice

It seems like this data is coming from DB. Also not all records are broken, but some are.

Thanks
Rajat Jindal

**Comment by stevepeak** [comment]
@rajatjindal welcome to our community and thank you for pointing this out. We are moving from our MVP to our v1 Asyncy Hub and some links changed/broke long that journey.

@JeanBarriere or @judepereira please fix these 👍

**Comment by judepereira** [comment]
@JeanBarriere Looks like it's just linking to the the `pull_url` field in `app_public.services`. However, this is incorrect. We need to get the owner/organisation from `app_public.owner_vcs`, and then get the repo name from `app_hidden.repos`.

**Comment by JeanBarriere** [comment]
@judepereira Indeed ! :+1:

**Comment by JeanBarriere** [comment]
fixed in PR #55
